// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm7USZEEjdVUpFrtsYQnRCUP65vTqU8uA',
    appId: '1:31457245766:web:669afdc52e6d40d400e847',
    messagingSenderId: '31457245766',
    projectId: 'dietapp-one',
    authDomain: 'dietapp-one.firebaseapp.com',
    storageBucket: 'dietapp-one.appspot.com',
    measurementId: 'G-CXR3E0VN7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4XfB-Cxfs2sinzsSOdaYHaOH0aGCj1WY',
    appId: '1:31457245766:android:9d429f85de94b35200e847',
    messagingSenderId: '31457245766',
    projectId: 'dietapp-one',
    storageBucket: 'dietapp-one.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0qj6KB1UkDt-YRFIbCWYmD7_5g80KF5g',
    appId: '1:31457245766:ios:3180a44868a3b95800e847',
    messagingSenderId: '31457245766',
    projectId: 'dietapp-one',
    storageBucket: 'dietapp-one.appspot.com',
    iosClientId: '31457245766-5ed6i44dtpttf6qbtv7vo5sddj0hnqr0.apps.googleusercontent.com',
    iosBundleId: 'com.example.dietRecipes',
  );
}
